services:
  # This is the name of your service on Render. 
  # You can find it in your dashboard URL (e.g., dashboard.render.com/web/srv-c...)
  # Or just give it a logical name.
  - type: web
    name: screen-recorder 
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gevent --workers 2 --timeout 300 --bind 0.0.0.0:$PORT 'app:app'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4 # Or your preferred Python version
      - key: MAIL_USERNAME
        fromSecret: MAIL_USERNAME
      - key: MAIL_PASSWORD
        fromSecret: MAIL_PASSWORD
      - key: SECRET_KEY
        fromSecret: SECRET_KEY